name: "Build & Deploy - RELEASE"
on:
  release:
    types: ["created"]

permissions: read-all

jobs:
  deploy:
    name: Deploy on VsCode MarketPlace
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: production
    steps:
      - uses: actions/checkout@v5
      - run: yarn
      - uses: lannonbr/vsce-action@510e61c5e9e6f33c0418ec5ff5fd36b1ced61e85 #4.0.0
        with:
          args: "publish -p $VSCE_TOKEN --allow-package-secrets github"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

#   deploy_ovsx:
#     name: Deploy on Open VSX
#     runs-on: ubuntu-latest
#     permissions: read-all
#     environment:
#       name: production
#     steps:
#       - uses: actions/checkout@v5
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 18
#       - run: yarn
#       - name: Publish to Open VSX Registry
#         uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db #v2
#         with:
#           pat: ${{ secrets.OPENVSX_TOKEN }}
